variant = "loose"

[[issues]]
file = "src/AbstractValidator.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/AbstractValidator.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/AbstractValidator.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 2

[[issues]]
file = "src/AbstractValidator.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "src/AbstractValidator.php"
code = "too-many-properties"
message = "Class has too many properties."
count = 1

[[issues]]
file = "src/BackedEnumValue.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "src/Barcode/Codabar.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 1

[[issues]]
file = "src/Barcode/Code128.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Barcode/Code128.php"
code = "halstead"
message = "Method has a high halstead difficulty and effort"
count = 1

[[issues]]
file = "src/Barcode/Code128.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/Barcode/Code128.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 11

[[issues]]
file = "src/Barcode/Code128.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 15

[[issues]]
file = "src/Barcode/Code93.php"
code = "strict-behavior"
message = "Call to `array_search` must enforce strict comparison."
count = 2

[[issues]]
file = "src/Barcode/Issn.php"
code = "no-insecure-comparison"
message = "Insecure comparison of sensitive data."
count = 1

[[issues]]
file = "src/Barcode/Issn.php"
code = "no-literal-password"
message = "Literal passwords or sensitive data should not be stored in code."
count = 1

[[issues]]
file = "src/Barcode/Royalmail.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/Barcode/Royalmail.php"
code = "strict-behavior"
message = "Call to `array_keys` must enforce strict comparison."
count = 2

[[issues]]
file = "src/Barcode/Util.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 3

[[issues]]
file = "src/Bitwise.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "src/BusinessIdentifierCode.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/CreditCard.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/CreditCard.php"
code = "halstead"
message = "Method has a high halstead difficulty and effort"
count = 1

[[issues]]
file = "src/CreditCard.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/CreditCard.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/CreditCard.php"
code = "strict-behavior"
message = "Call to `in_array` must enforce strict comparison."
count = 1

[[issues]]
file = "src/DateComparison.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/DateComparison.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "src/DateStep.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/DateStep.php"
code = "halstead"
message = "Method has a high halstead volume, difficulty, and effort"
count = 1

[[issues]]
file = "src/DateStep.php"
code = "identity-comparison"
message = "Use identity comparison `===` instead of equality comparison `==`."
count = 2

[[issues]]
file = "src/DateStep.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/DateStep.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 3

[[issues]]
file = "src/DateStep.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 2

[[issues]]
file = "src/DateStep.php"
code = "strict-behavior"
message = "Call to `in_array` must enforce strict comparison."
count = 2

[[issues]]
file = "src/EmailAddress.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/EmailAddress.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/EmailAddress.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/EmailAddress.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 1

[[issues]]
file = "src/EmailAddress.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "src/EmailAddress.php"
code = "no-shorthand-ternary"
message = "Use of the shorthand ternary operator."
count = 1

[[issues]]
file = "src/Explode.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Explode.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "src/File/ExcludeExtension.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/File/Extension.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/File/Extension.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/File/FileInformation.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/File/FileInformation.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "src/File/FilesSize.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/File/FilesSize.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "src/File/FilesSize.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "src/File/ImageSize.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/File/ImageSize.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "src/File/MimeType.php"
code = "strict-behavior"
message = "Call to `in_array` must enforce strict comparison."
count = 1

[[issues]]
file = "src/File/Size.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/File/Size.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "src/File/UploadFile.php"
code = "no-empty"
message = "Use of the `empty` construct."
count = 1

[[issues]]
file = "src/File/UploadFile.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "src/GpsPoint.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "src/HostWithPublicIPv4Address.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/Hostname.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Hostname.php"
code = "excessive-nesting"
message = "Excessive block nesting."
count = 3

[[issues]]
file = "src/Hostname.php"
code = "halstead"
message = "Method has a high halstead volume, difficulty, and effort"
count = 2

[[issues]]
file = "src/Hostname.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/Hostname.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 5

[[issues]]
file = "src/Hostname.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 4

[[issues]]
file = "src/Hostname.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 2

[[issues]]
file = "src/Hostname.php"
code = "no-nested-ternary"
message = "Nested ternary expressions are confusing due to PHP's operator associativity rules."
count = 3

[[issues]]
file = "src/Hostname.php"
code = "strict-behavior"
message = "Call to `in_array` must enforce strict comparison."
count = 2

[[issues]]
file = "src/Iban.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "src/Iban.php"
code = "strict-behavior"
message = "Call to `in_array` must enforce strict comparison."
count = 1

[[issues]]
file = "src/Identical.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Identical.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "src/Identical.php"
code = "identity-comparison"
message = "Use identity inequality `!==` instead of inequality comparison `!=`."
count = 1

[[issues]]
file = "src/Identical.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/Identical.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 2

[[issues]]
file = "src/Identical.php"
code = "no-literal-password"
message = "Literal passwords or sensitive data should not be stored in code."
count = 2

[[issues]]
file = "src/InArray.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/InArray.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "src/InArray.php"
code = "identity-comparison"
message = "Use identity comparison `===` instead of equality comparison `==`."
count = 1

[[issues]]
file = "src/InArray.php"
code = "strict-behavior"
message = "Call to `in_array` must enforce strict comparison."
count = 2

[[issues]]
file = "src/Ip.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Ip.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "src/Ip.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 2

[[issues]]
file = "src/IsCountable.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/IsJsonString.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/Isbn.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/NotEmpty.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/NotEmpty.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "src/NotEmpty.php"
code = "halstead"
message = "Method has a high halstead difficulty and effort"
count = 1

[[issues]]
file = "src/NotEmpty.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/NotEmpty.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 3

[[issues]]
file = "src/NumberComparison.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/NumberComparison.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "src/StringLength.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "src/Uri.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 2

[[issues]]
file = "src/ValidatorChain.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/ValidatorChain.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/ValidatorChain.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "src/ValidatorPluginManagerFactory.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "test/AbstractValidatorTest.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "test/EmailAddressTest.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "test/EmailAddressTest.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "test/File/IsCompressedTest.php"
code = "strict-behavior"
message = "Call to `in_array` must enforce strict comparison."
count = 3

[[issues]]
file = "test/HostnameTest.php"
code = "no-ini-set"
message = "ini_set should not be used."
count = 2

[[issues]]
file = "test/IdenticalTest.php"
code = "no-literal-password"
message = "Literal passwords or sensitive data should not be stored in code."
count = 7

[[issues]]
file = "test/IpTest.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 2

[[issues]]
file = "test/TestAsset/CustomTraversable.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1
