name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
    tags:

env:
  php_extensions: ctype,fileinfo,filter,intl
  default_php: 8.2

jobs:
  matrix:
    name: Generate job matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      -   name: Gather CI configuration
          id: matrix
          uses: laminas/laminas-ci-matrix-action@f48577eff9adecadd922d623be015e39ded8a972 # v1

  qa:
    name: QA Checks
    needs: [ matrix ]
    runs-on: ${{ matrix.operatingSystem }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
      -   name: ${{ matrix.name }}
          uses: laminas/laminas-continuous-integration-action@757a62736b25b11240101d3c616fff4cbc707cfd # v1
          with:
            job: ${{ matrix.job }}


  composer-require-checker:
    name: "Check for missing dependencies"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1

        with:
          php-version: ${{ env.default_php }}
          ini-values: memory_limit=-1
          extensions: ${{ env.php_extensions }}
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
      - run: make install-tools
      - run: make composer-require-checker
